# Generated by Django 3.2 on 2021-11-13 17:27

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=128)),
                ('ForeName', models.CharField(max_length=128, null=True)),
                ('Initials', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISSN', models.CharField(max_length=16)),
                ('Title', models.CharField(max_length=256)),
                ('ISOAbbreviation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeywordText', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('applicationText', models.TextField(max_length=512)),
                ('applicationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicationStatus', models.CharField(choices=[('1', 'New'), ('2', 'Approved'), ('3', 'Rejected')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationApplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikodeApp.registrationapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PMID', models.CharField(max_length=16)),
                ('Title', models.TextField(max_length=512)),
                ('Abstract', models.TextField(max_length=5000, null=True)),
                ('PublicationDate', models.DateField(null=True)),
                ('Tokens', models.TextField(max_length=100000)),
                ('SearchIndex', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('Authors', models.ManyToManyField(to='wikodeApp.Author')),
                ('Journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wikodeApp.journal')),
                ('Keywords', models.ManyToManyField(to='wikodeApp.Keyword')),
            ],
        ),
    ]
