# Generated by Django 3.2.9 on 2021-11-20 12:01

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikodeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagName', models.CharField(default='noname', max_length=64)),
                ('WikiID', models.CharField(max_length=64)),
                ('Label', models.CharField(max_length=64)),
                ('Description', models.TextField(max_length=1024, null=True)),
                ('Tokens', models.TextField(max_length=1024, null=True)),
                ('SearchIndex', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
    ]
