# Generated by Django 3.2.9 on 2021-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikodeApp', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='wikodeApp.Tag'),
        ),
    ]
